name: dartodo
description: Parse TODO comments from code
version: 0.1.0
repository: https://github.com/mab-eric313/dartodo

environment:
  sdk: ^3.12.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
